---
- name: Add Jenkins apt repository key.
  become: true
  apt_key:
    url: "{{ jenkins_repo_key_url }}"
    state: present

- name: Add Jenkins apt repository.
  become: true
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Ensure Jenkins is installed.
  become: true
  apt:
    name: jenkins
    state: present
    update_cache: yes
