---
- name: Ensure Jenkins repo is installed.
  become: true
  get_url:
    url: "{{ jenkins_repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo

- name: Add Jenkins repo GPG key.
  become: true
  rpm_key:
    state: present
    key: "{{ jenkins_repo_key_url }}"

- name: Ensure Jenkins is installed.
  become: true
  yum:
    pkg: jenkins
    state: installed
